# Generated by Django 4.2.3 on 2025-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_url_img_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_img',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
