# Generated by Django 5.2.6 on 2025-10-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(db_column='rating', default=0),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='_rating',
        ),
    ]
