# Generated by Django 5.2.6 on 2025-10-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_subscribers_delete_postscategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
