# Generated by Django 5.2.6 on 2025-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_category_subscribers_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='daily_post_limit',
            field=models.SmallIntegerField(default=3),
        ),
    ]
