# Generated by Django 5.2.6 on 2025-11-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
